
addons:
  apt:
    packages:
    - aria2
#before_install:
branches:
  only:
  - master

dist: trusty
rust:
- stable

#before_script:
script:
# When prefixed with `travis_wait 30`, no log output until it is done.
# see: https://github.com/travis-ci/travis-ci/issues/4190 or https://github.com/HaxeFoundation/hxcpp/issues/709
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- echo ${CI_OPT_DOCKER_REGISTRY_PASS} | docker login --password-stdin -u="${CI_OPT_DOCKER_REGISTRY_USER}" docker.io
- docker-compose build
- kill %1
#after_script:

services:
- docker
sudo: required
