
addons:
  apt:
    packages:
    - aria2
#before_install:
branches:
  only:
  - master

dist: trusty
env:
  global:
  - IMAGE_ARG_JAVA8_VERSION_BUILD=11

- IMAGE_ARG_JAVA8_VERSION_MINOR=171
- IMAGE_ARG_JAVA8_PACKAGE_DIGEST=512cd62ec5174c3487ac17c61aaa89e8 # 171
- IMAGE_ARG_JAVA8_VERSION_MINOR=172
- IMAGE_ARG_JAVA8_PACKAGE_DIGEST=a58eab1ec242421181065cdc37240b08 # 172

group: edge
install: true
language: rust

matrix:
  include:
  - env: IMAGE_ARG_JAVA8_VERSION_MINOR=171
    env: IMAGE_ARG_JAVA8_PACKAGE_DIGEST=512cd62ec5174c3487ac17c61aaa89e8
  - env: IMAGE_ARG_JAVA8_VERSION_MINOR=172
    env: IMAGE_ARG_JAVA8_PACKAGE_DIGEST=a58eab1ec242421181065cdc37240b08

rust:
  - stable

#before_script:
script:
# When prefixed with `travis_wait 30`, no log output until it is done.
# see: https://github.com/travis-ci/travis-ci/issues/4190 or https://github.com/HaxeFoundation/hxcpp/issues/709
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- echo ${CI_OPT_DOCKER_REGISTRY_PASS} | docker login --password-stdin -u="${CI_OPT_DOCKER_REGISTRY_USER}" docker.io
- docker-compose build
- kill %1
#after_script:

services:
- docker
sudo: required
