
version: '2.1'
services:
  java-8-oracle:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_ALPINE_MIRROR=${IMAGE_ARG_ALPINE_MIRROR:-mirror.tuna.tsinghua.edu.cn}
      - IMAGE_ARG_FILESERVER=${IMAGE_ARG_FILESERVER:-http://o9wbz99tz.bkt.clouddn.com}
      - IMAGE_ARG_GLIBC_VERSION=${IMAGE_ARG_GLIBC_VERSION:-2.23-r3}
      - IMAGE_ARG_JAVA8_VERSION_MINOR=${IMAGE_ARG_JAVA8_VERSION_MINOR:-171}
      - IMAGE_ARG_JAVA8_VERSION_BUILD=${IMAGE_ARG_JAVA8_VERSION_BUILD:-11}
      - IMAGE_ARG_JAVA8_PACKAGE_DIGEST=${IMAGE_ARG_JAVA8_PACKAGE_DIGEST:-512cd62ec5174c3487ac17c61aaa89e8}
    image: ${IMAGE_PREFIX:-cirepo}/java-8-oracle:${IMAGE_TAG:-8u171}
